version: '3'
services:  
  redis-sample:
    ports:
      - '6379:6379'
    container_name: redis-cache
    image: 'redis:latest'
    networks:
      - base-network


networks:
  base-network:
    driver: bridge